### ISSUE TITLE
Second player gets more time when delay is enabled

### ISSUE THREAD

**Issue by Ratfink** [simenheg/simple-chess-clock#1]
When either a Fischer or Bronstein delay is enabled, the second player gets extra time added at the start of their first turn.  This results in the second player having more time than the first.  To be fair, delays shouldn't be added until the start of the first player's second turn.

**Comment by simenheg** [comment]
Thanks for the report, @Ratfink, that's a good point. I think 2851e6537bccf3fcf34ca01891bf4e742bde08e9 should resolve the problem.

I opted to ensure that player 1 also gets a delay on the first turn instead of skipping it for player 2.
