### ISSUE TITLE
Feature: per-move time limit

### ISSUE THREAD

**Issue by shadow00** [simenheg/simple-chess-clock#18]
Instead of having a limit on total time, the limit is on the length of each turn (eg. 10 seconds each turn, so the game can potentially go on forever as long as the players are fast enough). Fischer/Bronstein do not apply for this timing mode.

As a second extra feature, these two limits could be combined (eg. 5 minute total game time, but each move can take max 10 seconds). Fischer/Bronstein *do* apply here because we still have a total time (though I'm not sure how Bronstein should interact with the turn time limit - perhaps only Fischer makes sense?).

Wish I could help with the implementation, but I am not familiar with Java/Android development at all.

**Comment by simenheg** [comment]
> Instead of having a limit on total time, the limit is on the length of each turn (eg. 10 seconds each turn, so the game can potentially go on forever as long as the players are fast enough). Fischer/Bronstein do not apply for this timing mode.

Maybe I'm misunderstanding what you mean, but can't this be achieved already by selecting game time 0 and setting a Bronstein delay to your desired turn limit?

**Comment by shadow00** [comment]
Just tested your suggestion: technically it works, though the timer doesn't actually stop when it reaches 0, but goes into negative numbers instead. Here's an example with 0 time and 5 second Bronstein delay:
![](https://i.imgur.com/ANO64Rq.jpg)  

Not sure if Bronstein is actually supposed to do that (go into negative time as long as total time + delay > 0) or if it's a glitch - but in this case it definitely doesn't make sense.

Besides, total time with delay looks rather unintuitive for this specific mode, imo. It would be nicer to have only the actual countdown instead. Otherwise it looks like everyone is always already at 0, which is confusing because total time doesn't actually matter in this case.

**Comment by simenheg** [comment]
> Just tested your suggestion: technically it works, though the timer doesn't actually stop when it reaches 0, but goes into negative numbers instead.

Ah! That used to work. It was a bug introduced in bffdb732296ec6e55ecbd8ed40a13766f1afc1e2, but should be fixed again now in 7d2a33ccb361edbd54e74288acb0dce825b1f570. Thanks for discovering it.

> Besides, total time with delay looks rather unintuitive for this specific mode, imo. It would be nicer to have only the actual countdown instead. Otherwise it looks like everyone is always already at 0, which is confusing because total time doesn't actually matter in this case.

I think it's alright even if it looks a bit weird; it should provide the functionality without introducing more menu choices (keeping the app simple, as in Simple Chess Clock ;)). I improved the display a bit in 190d6c564b56ac82e06a15a973e6ba6b2da346f1, making the delay appear on the same line as the total time when the "show deciseconds" option is turned off. Hope it will be sufficient for your use case!

**Comment by shadow00** [comment]
Cool! I'll give it a try when v2.6.2 is out on F-Droid.

**Comment by simenheg** [comment]
> Cool! I'll give it a try when v2.6.2 is out on F-Droid.

I tagged a new release now, so hopefully it should appear on F-Droid soon.
