### ISSUE TITLE
App is not taking full screen

### ISSUE THREAD

**Issue by meanindra** [simenheg/simple-chess-clock#22]
There are large margin at the bottom of the app
Check this screenshots https://imgur.com/a/obaPDl2
I am not sure this problem only with my device or not.

**Comment by meanindra** [comment]
Maybe bigger screen size users will face this issue.
My device
Size  6.3 inches, 97.4 cm2 (~81.4% screen-to-body ratio)
Resolution | 1080 x 2340 pixels, 19.5:9 ratio (~409 ppi density)

**Comment by meanindra** [comment]
I want o fix this problem but I am not able to run this app.
![image](https://user-images.githubusercontent.com/36324543/148340053-9559c1da-ca75-4990-8d9d-c3bbeb4210e6.png)
Can you help me to set up this?

**Comment by simenheg** [comment]
> I want to fix this problem but I am not able to run this app.

Thank you!

> Can you help me to set up this?

I'm building the app on [Debian](https://www.debian.org/) using the `Makefile` included the repository by running the following commands from the top level directory of the project:

```sh
make
make install
```

**Comment by simenheg** [comment]
@meanindra I believe the problem will be fixed by a0db9bd48cdd543db45ae9db0e588d6b71bdfa37.
