### ISSUE TITLE
Use weblate to manage translations

### ISSUE THREAD

**Issue by iNtEgraIR2021** [simenheg/simple-chess-clock#24]
As mentioned in #23 I'll suggest using [weblate.bubu1.eu](https://weblate.bubu1.eu) to manage the translations. Weblate integrates into the git workflow as a contributor and is an open source platform itself.

**Comment by iNtEgraIR2021** [comment]
To name an example: there's [currencies](https://github.com/sal0max/currencies) an currency converter. I suggested the use of weblate to the maintainer and today it's actively translated by the community in [8 languages](https://weblate.bubu1.eu/engage/currencies/).

**Comment by simenheg** [comment]
Thanks @iNtEgraIR2021, I think using such a service will be useful now that we're starting to accumulate more translations. I'll look into the site you suggest.

**Comment by comradekingu** [comment]
Happy to help

**Comment by iNtEgraIR2021** [comment]
@simenheg any news on this?

As #26 recently introduced another translation it should really ease the management of those in the future.

@comradekingu is one of weblate's main contributors so I'm he'll be happy to help with questions during the onboarding

**Comment by simenheg** [comment]
I've registered a project there to test it now. Let's see how it works out. :+1:

**Comment by comradekingu** [comment]
@simenheg Change the license to GPLv3-or-later as per 
>either version 3 of the License, or (at your option) any later version. 

from https://github.com/simenheg/simple-chess-clock
in https://weblate.bubu1.eu/settings/simple-chess-clock/android-app/ and
https://weblate.bubu1.eu/settings/simple-chess-clock/metadata/
:)

**Comment by simenheg** [comment]
> @simenheg Change the license to `GPLv3-or-later` as per
> 
> > either version 3 of the License, or (at your option) **any later version**.
> 
> from https://github.com/simenheg/simple-chess-clock in
> 
> https://weblate.bubu1.eu/settings/simple-chess-clock/android-app/ and https://weblate.bubu1.eu/settings/simple-chess-clock/metadata/ :)

I think I already did?

**Comment by comradekingu** [comment]
@simenheg If you ask bubu for the files you can move over to https://hosted.weblate.org/hosting/ :)
It is possible without, but then the history of who did what is lost.
Happy to help.
