### ISSUE TITLE
Adding Capped Fisher

### ISSUE THREAD

**Issue by TeXitoi** [simenheg/simple-chess-clock#28]
https://senseis.xmp.net/?CappedFischerTiming

That's basically Fisher Time, capped to the initial time. It allows to not have a lot of time by playing fast at the beginning. It's particularly interesting in go as you play a lot of move (like 150-200 for each player).

Limit time can be different to initial time, but to keep it simple, using the initial time would be enough.

And thanks for your great simple clock!

**Comment by simenheg** [comment]
Good idea, @TeXitoi!

Implemented in 6a06add669271da4519d57c213ef781a8fb21074.

**Comment by TeXitoi** [comment]
Thanks!
