### ISSUE TITLE
Used large amount of battery while idle

### ISSUE THREAD

**Issue by e00E** [simenheg/simple-chess-clock#29]
Thank you for making this app.

After installing the app I was playing around with settings and the clock. I stopped using the app by pressing the home button. At this point no timer was in progress. Later I noticed that my battery was draining more quickly than usual and the android battery settings showed the this app used a large percentage. After I force stopped the app battery usage went back to normal.

I'm not sure what happened on a technical level and I don't want to try reproducing this but still wanted to make the report. If you feel this is too vague then feel free to close the issue.

**Comment by simenheg** [comment]
Hi @e00E, thanks for your report.

I tried to reproduce this on two different phones by having the app running in the background, but it didn't seem to affect the battery levels. It's difficult to debug this further without having a reproducible recipe, so I'll close the issue for now, but please reopen it if you find a way to reproduce it, or if you get some suspicions on what might be causing the issue.

**Comment by simenheg** [comment]
It could be that commit 4ad5567955ae971bd31d8be1960474c87f7e2635 will fix this problem.
