### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [simenheg/simple-chess-clock#3]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by simenheg** [comment]
Thanks for the tip, @mondlicht-und-sterne.

I've tried adding it in 55d750f73baa61e68646c52544d58dc54133c72b. Hopefully it will appear in the next release!
