### ISSUE TITLE
Fischer delay doesn't work as intended

### ISSUE THREAD

**Issue by exgtfnum** [simenheg/simple-chess-clock#4]
In Fischer, a specified amount of time is added to the player's main time **after each move**, unless the player's main time ran out before they completed their move.

Right now the time get added at the start of the move.
The time should be added to P1's clock when P1 presses the button for P2's turn to start. (except the first time to start the clock)
Expected behavior at 1:06 : https://www.youtube.com/watch?v=X_mrstAkFlo&t=66

**Comment by simenheg** [comment]
Thanks @exgtfnum, I think you're right.

My Android build setup is seemingly broken at the moment, but I'll look into fixing this when I get it to work again.

**Comment by simenheg** [comment]
Should hopefully be fixed by d1078e4120a96e449e9edfbc4f9fdda471be8546.
