### ISSUE TITLE
support Bronstein delay with zero game time

### ISSUE THREAD

**Issue by derNarr** [simenheg/simple-chess-clock#7]
Hi, thanks for the nice app!

I would really like to use the Bronstein delay without any initial game time. But if I set the game time to 0 and hit the clock the alarm goes of immediately before the Bronstein seconds are added.

Would it be possible to first add the Bronstein time and then check if the time is zero?

I am not good in java, but if you can point me to the right file, I might be able to create a pull request.

Thanks!

**Comment by simenheg** [comment]
Hi @derNarr, thanks for the suggestion, that sounds like a useful feature.

Hopefully 2e6a038a15ba41514c4393bb03328ade54f276f3 should do the trick.

**Comment by derNarr** [comment]
Hi, thanks a lot. Now the version is out on F-Droid and I tested it and it works very nicely. Thanks!!
