### ISSUE TITLE
Add changelog to FDroid.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [simenheg/simple-chess-clock#8]
Example:
![Screenshot_20210606-121256_F-Droid.jpg](https://user-images.githubusercontent.com/59611881/120920722-8ad27180-c6c0-11eb-9359-e086c1a76c11.jpg)

**Comment by simenheg** [comment]
Hi @Glitchy-Tozier, thanks for your suggestion. Would you like to help me add the changelog to F-Droid?

**Comment by Glitchy-Tozier** [comment]
Unfortunately, I have pretty much zero knowledege about how to do anything on Fdroid  :/

**Comment by Sitavi** [comment]
You can add a folder named "changelogs" in "fastlane/metadata/en-US" (only English is sufficient for a changelog in my opinion) and create inside a new .txt file for each update. I just don't know if it works with only "metadata/en-US".
You can take an example from the source code of many F-Droid apps :)

**Comment by simenheg** [comment]
Ok, thanks @Sitavi. I'll look into that when making the next release.

**Comment by simenheg** [comment]
I made an attempt with 9ba68218c1adcc91cdb3b98336cb8bebe45c8e6a.
