### ISSUE TITLE
pause does not work with Bronstein time and zero game time

### ISSUE THREAD

**Issue by derNarr** [simenheg/simple-chess-clock#9]
Hi,

I realised two days ago that the pause does not work for Bronstein delay with zero game time as introduced with https://github.com/simenheg/simple-chess-clock/releases/tag/v2.3.0

If you click on the pause button it asks you, if you want to reset the clock.

Do you need more information on this bug?

Warm regards,

**Comment by simenheg** [comment]
Right, thanks for reporting! Should be fixed by c06e3f3c9fb2cf8bd54fd662cec509f82d70a6f2.
